export const DEFAULT_DIFFICULTY = 4;

export const DEFAULT_MINING_REWARD = 100;

export const DEFAULT_BLOCK_TIME = 10000;

export const GENESIS_BLOCK_PREVIOUS_HASH = "0";

export const MAX_TRANSACTIONS_PER_BLOCK = 10;
